CREATE TABLE Rentalcar
(

   CARID     BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   LOCATION    VARCHAR(40),
   CATEGORY    VARCHAR(10) NOT NULL,
   COST        DECIMAL(5,2),
   MAKE        VARCHAR(40),
   MODEL       VARCHAR(40),

   CONSTRAINT  PK_cAR  PRIMARY KEY(CARID)
);

 
